import mongooose from 'mongoose'

const paymentSchema = new mongooose.Schema({
    userId:{
        type:mongooose.Schema.Types.ObjectId,
        ref: "User",
        required: true
    },
    planId: String,
    amount: Number,
    credits: Number,
    razorpayOrderId: String,
    razorpayPaymentId: String,
    status:{
        type: String,
        enum: ["created", "paid", "failed"],
        default: "created"
    }
}, {timestamps:true})

const Payment = mongooose.model("Payment", paymentSchema)

export default Payment

/*
|==========================================================================
| FILE: Payment.model.js
| PURPOSE: Defines the Mongoose schema for the `payments` collection,
|          tracking Razorpay transactions and credit allocations.
|==========================================================================
|
| ROLE IN THE ARCHITECTURE
| ────────────────────────
| This file lives in the `server/models` layer. It is responsible for maintaining
| a verifiable audit trail of all financial transactions within the application.
| It links a user to a specific payment gateway order.
|
| IMPORTS & DEPENDENCIES
| ──────────────────────
| 1. `mongoose`: The ODM library used for defining the schema. (Note the typo `mongooose` in the import, which surprisingly works in JS if the package is installed that way or if it's an alias, but usually it's just a variable name holding the `mongoose` import).
|
| SCHEMA DEFINITION & DATA FLOW
| ─────────────────────────────
| [paymentSchema]
| - `userId`: ObjectId (ref: "User"). The buyer. Required.
| - `planId`: String. The internal identifier for the purchased package (e.g., "basic_plan").
| - `amount`: Number. The monetary value of the transaction.
| - `credits`: Number. The number of AI interview credits associated with this purchase.
| - `razorpayOrderId`: String. The unique Order ID generated by the Razorpay API before payment completion.
| - `razorpayPaymentId`: String. The unique Payment ID generated by Razorpay after successful checkout.
| - `status`: String. Tracks the lifecycle of the transaction (`created`, `paid`, `failed`). Defaults to `created`.
| - `timestamps: true`: Auto-manages `createdAt` and `updatedAt`.
|
| CONNECTIONS (Dependency Map)
| ───────────
| CONSUMED BY: 
|  - `payment.controller.js` (Creates the initial record with `status: "created"`, then updates it to `"paid"` upon webhook/signature verification).
| RELATES TO:
|  - `User.model.js` (Via the `userId` ObjectId).
|
| DESIGN PATTERNS
| ───────────────
| - **Audit Trail Pattern**: Financial systems must track the state of a payment before, during, and after the transaction. By creating a document with `status: "created"` before the user even enters their card details, we maintain a log of intent to purchase, which is crucial for resolving disputes.
|
| INTERVIEW QUESTIONS
| ───────────────────
| Q1: Why do we store both `razorpayOrderId` and `razorpayPaymentId`?
| A1: The `OrderId` represents the *intent* to pay and the required amount, generated server-side. The `PaymentId` represents the actual *transfer* of funds, generated by Razorpay client-side. We need both to securely verify the cryptographic HMAC signature sent by Razorpay during checkout completion.
|
| Q2: Why is `amount` stored as a Number, and how should currency be handled?
| A2: Razorpay handles amounts in the smallest currency unit (e.g., paise for INR, cents for USD) to avoid floating-point precision errors. Storing it as a Number allows us to easily verify if the paid amount matches the expected amount for the `planId`.
|
| Q3: What happens if a user closes the browser during payment?
| A3: The `Payment` document will remain in the database with the `status: "created"` indefinitely. This is normal and expected; it serves as an abandoned cart record.
|
| Q4: Why is there a typo in `import mongooose from 'mongoose'`?
| A4: In ES6 module syntax, the local variable name (`mongooose`) used in the `import` statement is arbitrary when importing a default export. While it functions perfectly, it is a typo that should be corrected for readability and to prevent confusion for other developers.
|
| Q5: How could this schema be improved for a production SaaS?
| A5: It lacks a `currency` field (e.g., "INR" or "USD") which is critical if expanding globally. Additionally, storing the raw `razorpaySignature` could be useful for historical auditing and dispute resolution.
|==========================================================================
*/